services:
  todo-backend-mongo:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db

  todo-backend-redis:
    image: redis:latest
    volumes:
      - redis_data:/data

  todo-backend:
    image: todo-backend-prod
    build:
      context: ./todo-backend
      dockerfile: Dockerfile
    environment:
      - MONGO_URL=mongodb://todo-backend-mongo:27017/the_database
      - REDIS_URL=redis://todo-backend-redis:6379
      - PORT=3000
      - NODE_ENV=production
    depends_on:
      - todo-backend-mongo
      - todo-backend-redis

  todo-frontend:
    image: todo-frontend
    build:
      context: ./todo-frontend
      dockerfile: Dockerfile
      args:
        VITE_BACKEND_URL: /api
    depends_on:
      - todo-backend
    container_name: todo-frontend-prod

  nginx:
    image: nginx:1.25-alpine
    container_name: reverse-proxy-prod
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - todo-backend

volumes:
  mongo_data:
  redis_data:
