services:
  blogapp-frontend:
    image: blogapp-frontend-dev
    volumes:
      - ./client/:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev -- --host

  blogapp-backend-mongo:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db

  blogapp-backend:
    image: blogapp-backend-dev
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_URL=mongodb://blogapp-backend-mongo:27017/database_db
    depends_on:
      - blogapp-backend-mongo
    command: npm run dev

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - blogapp-frontend
      - blogapp-backend

volumes:
  mongo_data:
